config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import accounts.views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo/',include('photo.urls')),
    path('c_type/',include('c_type.urls')),
    path('accounts/',include('accounts.urls')),
    path('',accounts.views.mainpage),
    path('notice/',include('notice.urls')),
    path('recommendApp/',include('recommendApp.urls')),
]
# urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)
# aws s3을 사용함으로써 제거

notice/urls.py
from django.urls import path
from . import views


app_name = 'notice'

urlpatterns = [
    path('notice/<int:notice_id>', views.detail, name="detail"),
    path('new/', views.new, name="new"),
    path('create', views.create, name="create"),
    path('newnotice/', views.noticepost, name="newnotice"),
    path('', views.notice, name="notice"),
    path('result/', views.result, name="result")
]

project/project/urls.py
from django.contrib import admin
from django.urls import path
import app.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', app.views.index, name='index'),
    path('result', app.views.result, name='result'),
]

urls.py
from django.urls import path
from .views import *


app_name = 'recommendApp'

urlpatterns = [
    path('',recommend_index,name='recommend_index'),
    path('result/',recommend_new, name='recommend_result'),

]

notice/models.py
from django.db import models

class Notice(models.Model):
    title = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]
    class Meta:
        ordering = ['-pub_date']

notice/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
from .models import Notice
from .form import NoticePost


def index(request):
    return render(request, 'recommend_index.html')


def detail(request, notice_id):
    details = get_object_or_404(Notice, pk=notice_id)  # 첫번째 인자는 어떤 클래스로부터 객체를 받을지, 두번째는 검색조건(pk)
    return render(request, 'notice_detail.html', {'details': details})


# new.html 띄워주는 함수
def new(request):
    return render(request, 'new.html')


# 입력받은 내용을 데이터베이스에 넣어주는 함수
def create(request):
    notice = Notice()
    notice.title = request.GET['title']
    notice.body = request.GET['body']
    notice.pub_date = timezone.datetime.now()
    notice.save()  # 쿼리셋 메소드 중 하나. 위의 객체를 데이터베이스에 저장해라. ex) 객체.delete : ~?
    return redirect('/notice/' + str(notice.id))


def noticepost(request):
    # 1. 입력된 내용을 처리하는 기능 -> POST
    if request.method == 'POST':
        form = NoticePost(request.POST)
        if form.is_valid():  # 잘 입력되었는지 확인
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            post.save()
            return redirect('notice')

    # 2. 빈 페이지를 띄워주는 기능 -> GET
    else:
        form = NoticePost()
        return render(request, 'new.html', {'form': form})


def notice(request):
    notices = Notice.objects  # 쿼리셋
    # 블로그 모든 글들을 대상으로
    notice_list = Notice.objects.all()
    # 블로그 객체 세 개를 한 페이지로 자르기
    paginator = Paginator(notice_list, 7)
    # request된 페이지가 뭔지를 알아내고 (request페이지를 변수에 담아내고)
    page = request.GET.get('page')
    # request된 페이지를 얻어온 뒤 return 해준다.
    posts = paginator.get_page(page)
    return render(request, 'notice.html', {'notices': notices, 'posts': posts})


def result(request):
    posts = Notice.objects.all()
    query = request.GET.get('query')
    if query:
        posts = posts.filter(title__icontains=query)
    return render(request, 'notice_result.html', {'posts': posts})

notice/templates/notice.html
{% extends 'base.html' %}
{% block title %}- 공지사항{% endblock %}

{% block content %}

<div class="content" style="position:relative; top:150px;">
    <div class="pull-right" style="position:relative; float:left; left:15%;">
        <form class="form-inline my-2 my-lg-0 pull-right" action="{% url 'notice:result' %}" method="GET">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="query">
            <button class="btn btn-success my-2 my-sm-0" type="submit">검색</button>
        </form>
    </div>
    <br>
    <div class="card-body" style="position:relative; top:150px;"></div>
        {% for notice in posts %}
        <div class="container">
            <div class="list-group">
                <a href="{% url 'notice:detail' notice.id %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{notice.title}}</h5>
                        <small class="text-muted">{{notice.pub_date|date:"Y년m월d일"}}</small>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    <br>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
            <a class="page-link" href="?page=1">처음</a>
            </li>
            {% if posts.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{posts.previous_page_number}}">이전</a>
            </li>
            {% endif %}

            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            <li class="page-item"><a class="page-link" href="?page=2">2</a></li>
            <li class="page-item"><a class="page-link" href="?page=3">3</a></li>

            {% if posts.has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{posts.next_page_number}}">다음</a>
            </li>
            {% endif %}
            <li class="page-item">
            <a class="page-link" href="?page={{posts.paginator.num_pages}}">마지막</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

notice/templates/notice_detail.html
{% extends 'base.html' %}
{% block title %}- 공지사항상세{% endblock %}

{% block content %}

<div class="container" style="position: relative; top:100px;">
    <br>
    <div class="card text-center">
        <div class="card-body">
            <h3 class="card-title">{{details.title}}</h3>
            <h6 class="card-subtitle mb-2 text-muted">{{details.pub_date|date:"Y년m월d일"}}</h6>
            <p class="card-text">{{details.body}}</p>
        </div>
    </div>
</div>
{% endblock %}

notice/templates/notice_result.html
{% extends 'base.html' %}
{% block title %}- 공지사항검색{% endblock %}

{% block content %}

<div class="content" style="position:relative; top:150px;">
    <div class="pull-right" style="position:relative; float:left; left:15%;">
        <form class="form-inline my-2 my-lg-0 pull-right" action="{% url 'notice:result' %}" method="GET">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="query">
            <button class="btn btn-success my-2 my-sm-0" type="submit">검색</button>
        </form>
    </div>
    <br>
    <div class="card-body" style="position:relative; top:150px;"></div>
        {% for notice in posts %}
            <div class="container">
                <div class="list-group">
                    <a href="{% url 'notice:detail' notice.id %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{notice.title}}</h5>
                            <small class="text-muted">{{notice.pub_date|date:"Y년m월d일"}}</small>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    <br>

</div>
{% endblock %}