config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import accounts.views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo/',include('photo.urls')),
    path('c_type/',include('c_type.urls')),
    path('accounts/',include('accounts.urls')),
    path('',accounts.views.mainpage),
    path('notice/',include('notice.urls')),
    path('recommendApp/',include('recommendApp.urls')),
]
# urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)
# aws s3을 사용함으로써 제거

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo'

urlpatterns = [
    path('',photo_list,name='photo_list'),
#    path('',PhotoListView.as_view(),name='photo_list'),
    path('detail/<int:pk>/',DetailView.as_view(model=Photo,template_name='photo/detail.html'),name='photo_detail'),
    path('upload/',PhotoUploadView.as_view(),name='photo_upload'),
    path('update/<int:pk>/',PhotoUpdateView.as_view(),name='photo_update'),
    path('delete/<int:pk>/',photo_delete,name='photo_delete'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path
import app.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', app.views.index, name='index'),
    path('result', app.views.result, name='result'),
]

urls.py
from django.urls import path
from .views import *


app_name = 'recommendApp'

urlpatterns = [
    path('',recommend_index,name='recommend_index'),
    path('result/',recommend_new, name='recommend_result'),

]

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Photo(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_photos')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']
    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")
    def summary(self):
        return self.text[:16]
    def get_absolute_url(self):
        return reverse('photo:photo_detail',args=[str(self.id)])

photo/views.py
from django.shortcuts import render,redirect
from .models import Photo
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.contrib.auth.decorators import login_required #함수형 뷰에 사용
from django.contrib.auth.mixins import LoginRequiredMixin #클래스형 뷰에 사용
from django.contrib.auth.models import User
from django.core.paginator import Paginator


@login_required
def photo_list(request):
    photos = Photo.objects.all()
    return render(request,'photo/list.html',{'photos':photos})

class PhotoUploadView(LoginRequiredMixin,CreateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/upload.html'
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/photo')
        else:
            return self.render_to_response({'form':form})

# class PhotoDeleteView(LoginRequiredMixin,DeleteView):
#     model = Photo
#     success_url = '/'
#     template_name = 'photo/delete.html'

def photo_delete(request,pk):
    post = Photo.objects.get(pk=pk)
    photos = Photo.objects.all()
    username=request.user.id
    if post.author_id == username:
        post.delete()
    return render(request,'photo/list.html',{'photos':photos})



class PhotoUpdateView(LoginRequiredMixin,UpdateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/update.html'

photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}- Delete{% endblock %}

{% block content %}
        <div class="row" style="position: relative; top:100px;">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <div class="alert alert-info">
                    Do you want to delete {{object}}?
                </div>
                <form action="" method="post">
                    {{form.as_p}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Confirm">
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
{{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
        <div class="row" style="position: relative; top:100px;">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{object.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btn btn-outline-primary btn-sm">
                    {{object.author.username}}</button>
                <p>{{object.text|linebreaksbr}}</p>
                <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
                    삭제하기
                </a>
                <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">
                    수정하기
                </a>
                {% load disqus_tags %}
<!--                disqus앱의 커스텀 태그를 사용하겠다는 의미-->
                {% disqus_show_comments %}
            </div>
            <div class="col-md-2"></div>
        </div>
{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %}
{% block title %}- 커뮤니티{% endblock %}

{% block content %}
<!--    <a href="{% url 'photo:photo_upload'%}" class="btn btn-xs btn-success" style="position: fixed; float:right; right:100px; top:100px;">글쓰기</a>-->
    {% for post in photos %}
        <div class="row float-left" style="width:33%; position: relative; top:100px;">
            <div class="col-md-3"></div>
            <div class="mycontent" style="width:300px;">
                <p><img src="{{post.photo.url}}" style="width:300px; height:300px;"></p>
                <button type="button" class="btn btn-xs btn-info">
                    작성자 : {{post.author.username}}</button>
                <p class="text-right" style="display:inline;float: right;">
                    <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
                </p><p></p>
                <p style="display:inline;">{{post.summary|linebreaksbr}}</p><a href="{%url 'photo:photo_detail' pk=post.id%}">...더보기</a>
                <br><br>
            </div>
            <div class="col-md-2"></div>
        </div>
    {% endfor %}

<!--<div class = "pagination" style="position:fixed; margin-left: -10%; left: 50%; bottom:30px;">-->
<!--    &lt;!&ndash; 페이징처리 시작 &ndash;&gt;-->
<!--    <ul class="pagination justify-content-center">-->
<!--        &lt;!&ndash; 이전페이지 &ndash;&gt;-->
<!--        {% if posts.has_previous %}-->
<!--        <li class="page-item">-->
<!--            <a class="page-link" href="?page={{ posts.previous_page_number }}">이전</a>-->
<!--        </li>-->
<!--        {% else %}-->
<!--        <li class="page-item disabled">-->
<!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>-->
<!--        </li>-->
<!--        {% endif %}-->
<!--        &lt;!&ndash; 페이지리스트 &ndash;&gt;-->
<!--        {% for page_number in posts.paginator.page_range %}-->
<!--        {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}-->
<!--            {% if page_number == posts.number %}-->
<!--            <li class="page-item active" aria-current="page">-->
<!--                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
<!--            </li>-->
<!--            {% else %}-->
<!--            <li class="page-item">-->
<!--                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
<!--            </li>-->
<!--            {% endif %}-->
<!--        {% endif %}-->
<!--        {% endfor %}-->
<!--        &lt;!&ndash; 다음페이지 &ndash;&gt;-->
<!--        {% if posts.has_next %}-->
<!--        <li class="page-item">-->
<!--            <a class="page-link" href="?page={{ posts.next_page_number }}">다음</a>-->
<!--        </li>-->
<!--        {% else %}-->
<!--        <li class="page-item disabled">-->
<!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>-->
<!--        </li>-->
<!--        {% endif %}-->
<!--    </ul>-->
<!--</div>-->
    <!-- 페이징처리 끝 -->

<!--<div class = "pagination" style="position:fixed; margin-left: -187.26px; left: 50%; bottom:10px;">-->
<!--    {#first previous#}-->
<!--    {% if posts.has_previous %}-->
<!--    <a href="?page=1">|첫페이지|</a>&nbsp;&nbsp;&nbsp;-->
<!--    <a href="?page={{posts.previous_page_number}}">|이전페이지|</a>&nbsp;&nbsp;&nbsp;-->
<!--    {% endif %}-->
<!--    {# 3of4 #}-->
<!--    <span>{{posts.number}}</span>-->
<!--    <span>of</span>-->
<!--    <span>{{posts.paginator.num_pages}}</span>-->
<!--    {# Next Last #}-->
<!--    {% if posts.has_next %}&nbsp;&nbsp;&nbsp;-->
<!--    <a href="?page={{posts.next_page_number}}">|다음페이지|</a>&nbsp;&nbsp;&nbsp;-->
<!--    <a href="?page={{posts.paginator.num_pages}}">|끝페이지|</a>-->
<!--    {%endif%}-->
<!--</div>-->

{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}- Update{% endblock %}

{% block content %}
        <div class="row" style="position: relative; top:100px;">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <form action="" method="post" enctype="multipart/form-data">
                    {{form.as_p}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Update">
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %}- Upload{% endblock %}

{% block content %}
        <div class="row" style="width:36%; position: relative; top:100px;">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <form action="" method="post" enctype="multipart/form-data">
                    {{form.as_p}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Upload">
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
{% endblock %}