accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register,mainpage

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_view.LoginView.as_view(),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register,name='register'),

]

blog/c_type/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('mbti/', views.mbti, name="mbti"),
    path('c_result/',views.c_result, name="c_result"),
]

c_type/urls.py
from django.urls import path
from .views import *


app_name = 'c_type'

urlpatterns = [
    path('',index,name='index'),
    path('result/',result, name='result'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import accounts.views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo/',include('photo.urls')),
    path('c_type/',include('c_type.urls')),
    path('accounts/',include('accounts.urls')),
    path('',accounts.views.mainpage),
    path('notice/',include('notice.urls')),
    path('recommendApp/',include('recommendApp.urls')),
]
# urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)
# aws s3을 사용함으로써 제거

notice/urls.py
from django.urls import path
from . import views


app_name = 'notice'

urlpatterns = [
    path('notice/<int:notice_id>', views.detail, name="detail"),
    path('new/', views.new, name="new"),
    path('create', views.create, name="create"),
    path('newnotice/', views.noticepost, name="newnotice"),
    path('', views.notice, name="notice"),
    path('result/', views.result, name="result")
]

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo'

urlpatterns = [
    path('',photo_list,name='photo_list'),
#    path('',PhotoListView.as_view(),name='photo_list'),
    path('detail/<int:pk>/',DetailView.as_view(model=Photo,template_name='photo/detail.html'),name='photo_detail'),
    path('upload/',PhotoUploadView.as_view(),name='photo_upload'),
    path('update/<int:pk>/',PhotoUpdateView.as_view(),name='photo_update'),
    path('delete/<int:pk>/',photo_delete,name='photo_delete'),

]

urls.py
from django.urls import path
from .views import *


app_name = 'recommendApp'

urlpatterns = [
    path('',recommend_index,name='recommend_index'),
    path('result/',recommend_new, name='recommend_result'),

]

blog/c_type/models.py
from django.db import models

class C_type(models.Model):
    q1 = models.BooleanField(default=False)
    q2 = models.BooleanField(default=False)
    q3 = models.BooleanField(default=False)
    q4 = models.BooleanField(default=False)
    q5 = models.BooleanField(default=False)
    q6 = models.BooleanField(default=False)
    q7 = models.BooleanField(default=False)
    q8 = models.BooleanField(default=False)

c_type/models.py
from django.db import models


class C_type(models.Model):
    q1 = models.BooleanField(default=False)
    q2 = models.BooleanField(default=False)
    q3 = models.BooleanField(default=False)
    q4 = models.BooleanField(default=False)
    q5 = models.BooleanField(default=False)
    q6 = models.BooleanField(default=False)
    q7 = models.BooleanField(default=False)
    q8 = models.BooleanField(default=False)

blog/c_type/views.py
from django.shortcuts import render, get_object_or_404
from .models import C_type
# Create your views here.

def mbti(request):
    return render(request, 'mbti.html')

def c_result(request):
    test = C_type()
    #A유형
    if(request.POST.get('q2')=='2'):
        if(request.POST.get('q5')=='1'):
            if(request.POST.get('q8')=='1'):
                return render(request, 'c_result.html', {'title':'함께하는 여행은 내 삶의 일부', 'c_result':'함께하는 여행을 선호하시는군요! 다양한 액티비티가 있어 함께 놀 수 있는 가평은 어떠신가요?'})
            else:
                return render(request, 'c_result.html', {'title':'혼자하는 여행은 내 삶의 일부', 'c_result':'혼자하는 즉흥적인 여행을 선호하시는군요! 조용하지만 볼거리가 많은 단양은 어떠신가요?'})
    #B유형
    if(request.POST.get('q3')=='1'):
        if(request.POST.get('q5')=='1'):
            if(request.POST.get('q8')=='1'):
                if(request.POST.get('q2')=='1'):
                    return render(request, 'c_result.html', {'title':'즉흥적이지만 여행은 알차게', 'c_result':'전주에서 친구, 가족과 함께 핫플, 맛집 탐방과 인생샷을 남기기 위한 여행을 하는건 어떠신가요?'})
                else:
                    return render(request, 'c_result.html', {'title':'여행을 계획적으로 알차게', 'c_result':'계획을 세워 알차레 여행하는 것을 좋아하시는군요! 관광할 것이 많은 제주도는 어떠신가요?'})
    #C유형
    if(request.POST.get('q2')=='2'):
        if(request.POST.get('q3')=='1'):
            if(request.POST.get('q5')=='1'):
                return render(request, 'c_result.html', {'title':'여행은 또 다른 배움터', 'c_result':'조용한 곳에서 여행을 즐기며 새로운 걸 배우는 것을 좋아하시나요? 천년의 역사가 담긴 경주를 추천합니다!'})

    #D유형
    if(request.POST.get('q4')=='1'):
        if(request.POST.get('q7')=='1'):
            if(request.POST.get('q8')=='2'):
                return render(request, 'c_result.html', {'title':'조용한 힐링이 필요해', 'c_result':'이번 휴가엔 좋은 숙소에서 야경을 보며 혼자 힐링하는 것은 어떠신가요? 바다가 예쁜 속초를 추천합니다!'})
            else:
                return render(request, 'c_result.html', {'title':'함께하는 힐링이 필요해', 'c_result':'여수에서 밤바다를 보며 힐링하는건 어떠신가요? 새로운 인연을 만나게 될지도 몰라요!'})
    #E유형
    if(request.POST.get('q1')=='2'):
        if(request.POST.get('q4')=='1'):
            if(request.POST.get('q7')=='1'):
                if(request.POST.get('q5')=='1'):
                    return render(request, 'c_result.html', {'title':'좋은 풍경을 좋아하는 사람과 함께', 'c_result':'오션뷰가 멋있는 강릉에서 내가 좋아하는 사람과 함께 여행 하는건 어떠신가요?'})
                else:
                    return render(request, 'c_result.html', {'title':'좋은 볼거리을 좋아하는 사람과 함께', 'c_result':'볼거리와 맛집이 많은 서울에서 내가 좋아하는 사람과 호캉스를 하는건 어떠신가요?'})

    return render(request, 'c_result.html', {'title':'여행자의 파라다이스', 'c_result':'힐링, 액티비티, 멋진 뷰 모든걸 만족할 수 있는 다양한 여행지를 찾고계신가요? 여행자의 파라다이스 부산을 추천합니다!'})


c_type/views.py
from django.shortcuts import render, get_object_or_404
from .models import C_type
# Create your views here.

def index(request):
    return render(request, 'index.html')

def result(request):
    test = C_type()
    #A유형
    if(request.POST.get('q2')=='2'):
        if(request.POST.get('q5')=='1'):
            if(request.POST.get('q8')=='1'):
                return render(request, 'result.html', {'title':'함께하는 여행은 내 삶의 일부', 'result':'함께하는 여행을 선호하시는군요! 다양한 액티비티가 있어 함께 놀 수 있는 가평은 어떠신가요?'})
            else:
                return render(request, 'result.html', {'title':'혼자하는 여행은 내 삶의 일부', 'result':'혼자하는 즉흥적인 여행을 선호하시는군요! 조용하지만 볼거리가 많은 단양은 어떠신가요?'})
    #B유형
    if(request.POST.get('q3')=='1'):
        if(request.POST.get('q5')=='1'):
            if(request.POST.get('q8')=='1'):
                if(request.POST.get('q2')=='1'):
                    return render(request, 'result.html', {'title':'즉흥적이지만 여행은 알차게', 'result':'전주에서 친구, 가족과 함께 핫플, 맛집 탐방과 인생샷을 남기기 위한 여행을 하는건 어떠신가요?'})
                else:
                    return render(request, 'result.html', {'title':'여행을 계획적으로 알차게', 'result':'계획을 세워 알차레 여행하는 것을 좋아하시는군요! 관광할 것이 많은 제주도는 어떠신가요?'})
    #C유형
    if(request.POST.get('q2')=='2'):
        if(request.POST.get('q3')=='1'):
            if(request.POST.get('q5')=='1'):
                return render(request, 'result.html', {'title':'여행은 또 다른 배움터', 'result':'조용한 곳에서 여행을 즐기며 새로운 걸 배우는 것을 좋아하시나요? 천년의 역사가 담긴 경주를 추천합니다!'})

    #D유형
    if(request.POST.get('q4')=='1'):
        if(request.POST.get('q7')=='1'):
            if(request.POST.get('q8')=='2'):
                return render(request, 'result.html', {'title':'조용한 힐링이 필요해', 'result':'이번 휴가엔 좋은 숙소에서 야경을 보며 혼자 힐링하는 것은 어떠신가요? 바다가 예쁜 속초를 추천합니다!'})
            else:
                return render(request, 'result.html', {'title':'함께하는 힐링이 필요해', 'result':'여수에서 밤바다를 보며 힐링하는건 어떠신가요? 새로운 인연을 만나게 될지도 몰라요!'})
    #E유형
    if(request.POST.get('q1')=='2'):
        if(request.POST.get('q4')=='1'):
            if(request.POST.get('q7')=='1'):
                if(request.POST.get('q5')=='1'):
                    return render(request, 'result.html', {'title':'좋은 풍경을 좋아하는 사람과 함께', 'result':'오션뷰가 멋있는 강릉에서 내가 좋아하는 사람과 함께 여행 하는건 어떠신가요?'})
                else:
                    return render(request, 'result.html', {'title':'좋은 볼거리을 좋아하는 사람과 함께', 'result':'볼거리와 맛집이 많은 서울에서 내가 좋아하는 사람과 호캉스를 하는건 어떠신가요?'})

    return render(request, 'result.html', {'title':'여행자의 파라다이스', 'result':'힐링, 액티비티, 멋진 뷰 모든걸 만족할 수 있는 다양한 여행지를 찾고계신가요? 여행자의 파라다이스 부산을 추천합니다!'})

c_type/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>여행타입 테스트</title>
    <link rel="icon" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/img/Fevicon.png" type="image/png">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/linericon/style.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/flat-icon/font/flaticon.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/nice-select/nice-select.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/css/style.css">
    <script src="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/js/main.js"></script>
  <style>
    html{
      width: 100%;
      height: 100%;
    }
    form {
      margin: 0 auto;
      display: inline;
    }
    body {
      width: 100%;
      height: 100%;
      justify-content: center;
      font-family: sans-serif;
      display: flex;
     background-color: #f8f8ff;


    }
    .container{
      width: 100%;
      height: 100%;
    }
    h2{
      padding-top: 20px;
      text-align: center;
      color: white;
      font-size: 60px;

    }
    p{
      text-align: center;
      color: white;
      font-size: larger;
    }
    h4{
    color:	#696969;

    }
    .rdo-grp label {
      cursor: pointer;
      -webkit-tap-highlight-color: transparent;
      padding: 6px 8px;
      border-radius: 20px;
      float: left;
      transition: all 0.2s ease;

    }
    .rdo-grp label:hover {
      background: rgba(125,100,247,0.06);
    }
    .rdo-grp label:not(:last-child) {
      margin-right: 16px;
    }
    .rdo-grp label span {
      vertical-align: middle;
    }
    .rdo-grp label span:first-child {
      position: relative;
      display: inline-block;
      vertical-align: middle;
      width: 20px;
      height: 20px;
      background: #e8eaed;
      border-radius: 50%;
      transition: all 0.2s ease;
      margin-right: 8px;
    }
    .rdo-grp label span:first-child:after {
      content: '';
      position: absolute;
      width: 16px;
      height: 16px;
      margin: 2px;
      background: #fff;
      border-radius: 50%;
      transition: all 0.2s ease;
    }
    .rdo-grp label:hover span:first-child {
      background: #7d64f7;
    }
    .rdo-grp input  {
      display: none;
    }
    .rdo-grp input:checked + label span:first-child {
      background: #7d64f7;
    }
    .rdo-grp input:checked + label span:first-child:after {
      transform: scale(0.5);
    }

    input[type="submit"]{
      background: #7d64f7;
      color:#fff;
      border: none;
      border-radius:5px;
      box-shadow: 0 0 5px gray;
      position:relative;
      height:50px;
      font-size:1.0em;
      padding:0 2em;
      cursor:pointer;
      transition:800ms ease all;
      outline:none;
    }
    input[type="submit"]:hover{
      background:#f8f8ff;
      color:#7d64f7;
      text-align:right;
    }
    input[type="submit"]:before,button:after{
      content:'';
      position:absolute;
      top:0;
      right:0;
      height:2px;
      width:50%;
      background:#f8f8ff;
      transition:400ms ease all;
    }
    input[type="submit"]:after{
      right:inherit;
      top:inherit;
      left:0;
      bottom:0;
    }
    input[type="submit"]:hover:before,button:hover:after{
      width:50%;
      transition:800ms ease all;
    }
    #div1{
      padding-bottom: 80px;
      width: 100%;
      height: 140px;
      background-color: #a39ffa;
    }
    #div2{
      position: absolute;
      left: 50%;
      top:70%;
      transform: translate(-50%, -50%);
    }
    </style>
</head>
<body>

 <header class="header_area">
     <div class="main_menu">
         <nav class="navbar navbar-expand-lg navbar-light">
             <div class="container box_1620">
                 <a class="navbar-brand logo_h" href="/"></a>
                 <a class="button" href="/">또바기</a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse"
                         data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                         aria-expanded="false" aria-label="Toggle navigation">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                 </button>

                 <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                     <ul class="nav navbar-nav menu_nav justify-content-end">
                         <li class="nav-item active"><a class="nav-link" href="/">HOME</a></li>
                         {% if user.is_authenticated %}
                         <li class="nav-item"><a class="nav-link" href="#" class="nav-link">반갑습니다, {{user.get_username}}님!</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" class="nav-link">로그아웃</a></li>
                         {% else %}
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" class="nav-link">로그인</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}" class="nav-link">회원가입</a></li>
                         {% endif %}
                         <li class="nav-item submenu dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">추천 테스트</a>
                         <ul class="dropdown-menu">
                             <li class="nav-item"><a class="nav-link" href="{%url 'recommendApp:recommend_index' %}">여행지 추천</a>
                             <li class="nav-item"><a class="nav-link" href="{%url 'c_type:index' %}">성격유형</a>
                         </ul></li>
<!--                         <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}" class="nav-link">커뮤니티</a></li>-->
                         <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                              aria-expanded="false">커뮤니티</a>
                            <ul class="dropdown-menu">
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}">글 목록</a></li>
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_upload' %}">글 작성</a></li>
                            </ul>
                         </li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'notice:notice' %}">공지사항</a></li>
                     </ul>
                 </div>
             </div>
         </nav>
     </div>
 </header>
 <div class="container" style="position:relative; top:100px;">
  <div class="row" id ="div1"><br><br>
    <h2 >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;나의 여행 스타일에 맞는 여행타입은? </h2>
    <p><b>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;
        간단한 테스트를 통해 나의 여행 스타일에 맞는 여행타입을 알 수 있어요
  </b></p>
  </div>
  <div class="row" id="div2">
    <form action="{% url 'c_type:result' %}" method="POST"> {% csrf_token %}
      <div class="rdo-grp">

          <h4> Q1. 나는 먼 곳으로 여행가는 것을 좋아한다</h4>

      <input type="radio" name="q1" value="1" id="c1"/>
          <label for="c1"><span></span><span>YES</span></label>
      <input type="radio" name="q1" value="2" id="c2"/>
       <label for="c2"><span></span><span>NO</span></label>
  <br> <br>

          <h4>Q2. 나의 여행은 세운 계획대로 진행되어야한다 </h4>

          <input type="radio" name="q2" value="1" id="c3">
                <label for="c3"><span></span><span>YES</span></label>
      <input type="radio" name="q2" value="2" id="c4"/>
          <label for="c4"><span></span><span>NO</span></label>
      <br> <br>

     <h4>Q3. 나는 여행을 갔을때<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 그 지역의 유명 관광지는 꼭 방문해야한다</h4>

       <input type="radio" name="q3" value="1" id="c5">
                <label for="c5"><span></span><span>YES</span></label>
      <input type="radio" name="q3" value="2" id="c6"/>
          <label for="c6"><span></span><span>NO</span></label>
      <br> <br>

          <h4>Q4. 나에게 여행할 때 가장 중요한 것은 음식이다 <br></h4>

      <input type="radio" name="q4" value="1" id="c7">
                <label for="c7"><span></span><span>YES</span></label>
      <input type="radio" name="q4" value="2" id="c8"/>
          <label for="c8"><span></span><span>NO</span></label>
      <br> <br>

          <h4>Q5. 나는 새로운 곳으로 여행가는 것을 좋아한다</h4>
      <input type="radio" name="q5" value="1" id="c9">
                <label for="c9"><span></span><span>YES</span></label>
      <input type="radio" name="q5" value="2" id="c10"/>
          <label for="c10"><span></span><span>NO</span></label>
      <br> <br>

          <h4>Q6. 나는 누군가와 함께하는 여행이 더 즐겁다 <br></h4>
      <input type="radio" name="q6" value="1" id="c11">
                <label for="c11"><span></span><span>YES</span></label>
      <input type="radio" name="q6" value="2" id="c12"/>
          <label for="c12"><span></span><span>NO</span></label>
      <br> <br>

          <h4>Q7. 나의 여행에서 좋은 숙소는 중요하다 <br></h4>
      <input type="radio" name="q7" value="1" id="c13">
                <label for="c13"><span></span><span>YES</span></label>
      <input type="radio" name="q7" value="2" id="c14"/>
          <label for="c14"><span></span><span>NO</span></label>
      <br> <br>

          <h4>Q8. 나는 여행에서 처음 만난 사람과 <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 쉽게 말을 나눌 수 있다 <br></h4>
      <input type="radio" name="q8" value="1" id="c15">
                <label for="c15"><span></span><span>YES</span></label>
      <input type="radio" name="q8" value="2" id="c16"/>
          <label for="c16"><span></span><span>NO</span></label>
      <br>
          </div>
          <br><br><br>
          <div style="margin-left: 30%;">
      <input type="submit" class="button" value="결과 보러가기">
              <br><br><br><br><br><br>
    </div>
  </form>
  </div>
  </div>
</body>
</html>

c_type/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>여행타입 테스트</title>
    <link rel="icon" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/img/Fevicon.png" type="image/png">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/linericon/style.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/flat-icon/font/flaticon.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/nice-select/nice-select.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/css/style.css">
    <script src="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/js/main.js"></script>
  <style>
    body {
     font-family: sans-serif;
    }
    h2{
    color: white;
    padding-top: 30px;
    font-size: 50px;
    }
    #div1{
      text-align: center;
      background-color: #a39ffa;
    }
    #div1 p{
      font-size: 25px;
      padding-bottom: 20px;
      color: white;
    }
    #div2{
      font-size: 23px;
      text-align: center;
      padding-top: 75px;
    }
    </style>
</head>
<body>


 <header class="header_area">
     <div class="main_menu">
         <nav class="navbar navbar-expand-lg navbar-light">
             <div class="container box_1620">
                 <a class="navbar-brand logo_h" href="/"></a>
                 <a class="button" href="/">또바기</a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse"
                         data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                         aria-expanded="false" aria-label="Toggle navigation">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                 </button>

                 <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                     <ul class="nav navbar-nav menu_nav justify-content-end">
                         <li class="nav-item active"><a class="nav-link" href="/">HOME</a></li>
                         {% if user.is_authenticated %}
                         <li class="nav-item"><a class="nav-link" href="#" class="nav-link">반갑습니다, {{user.get_username}}님!</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" class="nav-link">로그아웃</a></li>
                         {% else %}
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" class="nav-link">로그인</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}" class="nav-link">회원가입</a></li>
                         {% endif %}
                         <li class="nav-item submenu dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">추천 테스트</a>
                         <ul class="dropdown-menu">
                             <li class="nav-item"><a class="nav-link" href="{%url 'recommendApp:recommend_index' %}">여행지 추천</a>
                             <li class="nav-item"><a class="nav-link" href="{%url 'c_type:index' %}">성격유형</a>
                         </ul></li>
<!--                         <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}" class="nav-link">커뮤니티</a></li>-->
                         <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                              aria-expanded="false">커뮤니티</a>
                            <ul class="dropdown-menu">
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}">글 목록</a></li>
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_upload' %}">글 작성</a></li>
                            </ul>
                         </li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'notice:notice' %}">공지사항</a></li>
                     </ul>
                 </div>
             </div>
         </nav>
     </div>
 </header>
  <div class="container" style="position:relative; top:100px;">
      <div id="div1">
        <h2 >여행타입 테스트 결과 🚅</h2>
        <p >"{{title}}"</p>
      </div>
      <div class="row" id="div2">
        <strong style="color:black;">
        <p>{{user.get_username}}님의 여행타입 테스트 결과는 "{{title}}" 로 나왔습니다!
          <br>
          또바기에서 {{user.get_username}}님께 추천드리는 여행:
        </p>{{result}}
      </strong>
      </div>
  </div>


</body>
</html>