accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register,mainpage

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_view.LoginView.as_view(),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register,name='register'),

]

c_type/urls.py
from django.urls import path
from .views import *


app_name = 'c_type'

urlpatterns = [
    path('',index,name='index'),
    path('result/',result, name='result'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import accounts.views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo/',include('photo.urls')),
    path('c_type/',include('c_type.urls')),
    path('accounts/',include('accounts.urls')),
    path('',accounts.views.mainpage),
    path('notice/',include('notice.urls')),
    path('recommendApp/',include('recommendApp.urls')),
]
# urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)
# aws s3을 사용함으로써 제거

notice/urls.py
from django.urls import path
from . import views


app_name = 'notice'

urlpatterns = [
    path('notice/<int:notice_id>', views.detail, name="detail"),
    path('new/', views.new, name="new"),
    path('create', views.create, name="create"),
    path('newnotice/', views.noticepost, name="newnotice"),
    path('', views.notice, name="notice"),
    path('result/', views.result, name="result")
]

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo'

urlpatterns = [
    path('',photo_list,name='photo_list'),
#    path('',PhotoListView.as_view(),name='photo_list'),
    path('detail/<int:pk>/',DetailView.as_view(model=Photo,template_name='photo/detail.html'),name='photo_detail'),
    path('upload/',PhotoUploadView.as_view(),name='photo_upload'),
    path('update/<int:pk>/',PhotoUpdateView.as_view(),name='photo_update'),
    path('delete/<int:pk>/',photo_delete,name='photo_delete'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path
import app.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', app.views.index, name='index'),
    path('result', app.views.result, name='result'),
]

recommendApp/urls.py
from django.urls import path
from .views import *


app_name = 'recommendApp'

urlpatterns = [
    path('',recommend_index,name='recommend_index'),
    path('result/',recommend_new, name='recommend_result'),

]

urls.py
from django.urls import path
from .views import *


app_name = 'recommendApp'

urlpatterns = [
    path('',recommend_index,name='recommend_index'),
    path('result/',recommend_new, name='recommend_result'),

]

recommendApp/models.py
from django.db import models

# Create your models here.
class Test(models.Model):
    name = models.CharField('NAME', max_length=100, blank=False)
    local = models.CharField('LOCAL', max_length=100, blank=False)
    rating = models.IntegerField()
    q1 = models.BooleanField(default=False)
    q2 = models.BooleanField(default=False)
    q3 = models.BooleanField(default=False)
    def __str__(self):
        return self.name

recommendApp/views.py
from django.shortcuts import render
# from django.http import HttpResponse
# from Untitled import test
from .models import Test

import pandas as pd
import csv
import surprise

import warnings


# Create your views here.

# def bar(request):


def recommend_index(request):
    test = Test.objects
    return render(request, 'recommend_index.html', {'tests': test})


def recommend_new(request):
    test = Test()
    test.name = request.POST.get('name')
    test.local = request.POST.get('local')
    test.rating = request.POST.get('rating')
    test.save()

    if (request.POST.get('q1') == '1'):
        if (request.POST.get('q2') == '1'):
            if (request.POST.get('q3') == '1'):
                f = open('뚜벅혼자관광.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('뚜벅혼자관광.csv', encoding="utf-8", sep=",")
            elif (request.POST.get('q3') == '2'):
                f = open('뚜벅혼자휴양.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('뚜벅혼자휴양.csv', encoding="utf-8", sep=",")
        elif (request.POST.get('q2') == '2'):
            if (request.POST.get('q3') == '1'):
                f = open('뚜벅2인관광.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('뚜벅2인관광.csv', encoding="utf-8", sep=",")

            elif (request.POST.get('q3') == '2'):
                f = open('뚜벅2인휴양.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('뚜벅2인휴양.csv', encoding="utf-8", sep=",")
        elif (request.POST.get('q2') == '3'):
            if (request.POST.get('q3') == '1'):
                f = open('뚜벅3인관광.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('뚜벅3인관광.csv', encoding="utf-8", sep=",")

            elif (request.POST.get('q3') == '2'):
                f = open('뚜벅3인휴양.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('뚜벅3인휴양.csv', encoding="utf-8", sep=",")

    elif (request.POST.get('q1') == '2'):
        if (request.POST.get('q2') == '1'):
            if (request.POST.get('q3') == '1'):
                f = open('자차혼자관광.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('자차혼자관광.csv', encoding="utf-8", sep=",")
            elif (request.POST.get('q3') == '2'):
                f = open('자차혼자휴양.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('자차혼자휴양.csv', encoding="utf-8", sep=",")
        elif (request.POST.get('q2') == '2'):
            if (request.POST.get('q3') == '1'):
                f = open('자차2인관광.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('자차2인관광.csv', encoding="utf-8", sep=",")

            elif (request.POST.get('q3') == '2'):
                f = open('자차2인휴양.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('자차2인휴양.csv', encoding="utf-8", sep=",")
        elif (request.POST.get('q2') == '2'):
            if (request.POST.get('q3') == '3'):
                f = open('자차3인관광.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('자차3인관광.csv', encoding="utf-8", sep=",")

            elif (request.POST.get('q3') == '2'):
                f = open('자차3인휴양.csv', 'a', newline='', encoding='utf-8')
                wr = csv.writer(f)
                wr.writerow([test.name, test.local, test.rating])
                f.close()

                warnings.filterwarnings('ignore')
                data = pd.read_csv('자차3인휴양.csv', encoding="utf-8", sep=",")

    df = data[['id', '여행지', 'rating']]

    def recur_dictify(frame):
        if len(frame.columns) == 1:
            if frame.values.size == 1: return frame.values[0][0]
            return frame.values.squeeze()
        grouped = frame.groupby(frame.columns[0])
        d = {k: recur_dictify(g.iloc[:, 1:]) for k, g in grouped}
        return d

    df_to_dict = recur_dictify(df)

    name_list = []
    cos_set = set()

    for user_key in df_to_dict:
        name_list.append(user_key)
        for cos_key in df_to_dict[user_key]:
            cos_set.add(cos_key)

    local_list = list(cos_set)

    rating_dic = {
        'id': [],
        '여행지': [],
        'rating': []
    }

    for name_key in df_to_dict:
        for cos_key in df_to_dict[name_key]:
            a1 = name_list.index(name_key)
            a2 = local_list.index(cos_key)
            a3 = df_to_dict[name_key][cos_key]

            rating_dic['id'].append(a1)
            rating_dic['여행지'].append(a2)
            rating_dic['rating'].append(a3)

    df = pd.DataFrame(rating_dic)

    reader = surprise.Reader(rating_scale=(1, 10))
    data = surprise.Dataset.load_from_df(df[['id', '여행지', 'rating']], reader)

    trainset = data.build_full_trainset()
    option = {'name': 'pearson'}
    algo = surprise.KNNBasic(sim_options=option)

    algo.fit(trainset)

    index = name_list.index(test.name)
    result = algo.get_neighbors(index, k=2)

    def localtest():
        for r1 in result:
            max_rating = data.df[data.df["id"] == r1]["rating"].max()
            local_id = data.df[(data.df["rating"] == max_rating) & (data.df["id"] == r1)]["여행지"].values
            for local_item in local_id:
                return (local_list[local_item])

    return render(request, 'recommend_result.html', {'localtest': localtest})

recommendApp/templates/recommend_index.html
<!doctype html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>맞춤형 추천 여행지 테스트</title>
    <link rel="icon" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/img/Fevicon.png" type="image/png">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/linericon/style.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/flat-icon/font/flaticon.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/nice-select/nice-select.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/css/style.css">
    <script src="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/js/main.js"></script>
    <style>
    html{
      width: 100%;
      height: 100%;
    }
    form {
      margin: 0 auto;
      display: inline;
    }
    body {
      width: 100%;
      height: 100%;
      justify-content: center;
      font-family: sans-serif;
      display: flex;
     background-color: #f8f8ff;


    }
    .container{
      width: 100%;
      height: 100%;
    }
    h2{
      padding-top: 20px;
      text-align: center;
      color: white;
      font-size: 60px;

    }
    p{
      text-align: center;
      color: white;
      font-size: larger;
    }
    h4{
    color:	#696969;

    }
    .rdo-grp label {
      cursor: pointer;
      -webkit-tap-highlight-color: transparent;
      padding: 6px 8px;
      border-radius: 20px;
      float: left;
      transition: all 0.2s ease;

    }
    .rdo-grp label:hover {
      background: rgba(125,100,247,0.06);
    }
    .rdo-grp label:not(:last-child) {
      margin-right: 16px;
    }
    .rdo-grp label span {
      vertical-align: middle;
    }
    .rdo-grp label span:first-child {
      position: relative;
      display: inline-block;
      vertical-align: middle;
      width: 20px;
      height: 20px;
      background: #e8eaed;
      border-radius: 50%;
      transition: all 0.2s ease;
      margin-right: 8px;
    }
    .rdo-grp label span:first-child:after {
      content: '';
      position: absolute;
      width: 16px;
      height: 16px;
      margin: 2px;
      background: #fff;
      border-radius: 50%;
      transition: all 0.2s ease;
    }
    .rdo-grp label:hover span:first-child {
      background: #7d64f7;
    }
    .rdo-grp input  {
      display: none;
    }
    .rdo-grp input:checked + label span:first-child {
      background: #7d64f7;
    }
    .rdo-grp input:checked + label span:first-child:after {
      transform: scale(0.5);
    }

    input[type="submit"]{
      background: #7d64f7;
      color:#fff;
      border: none;
      border-radius:5px;
      box-shadow: 0 0 5px gray;
      position:relative;
      height:50px;
      font-size:1.0em;
      padding:0 2em;
      cursor:pointer;
      transition:800ms ease all;
      outline:none;
    }
    input[type="submit"]:hover{
      background:#f8f8ff;
      color:#7d64f7;
      text-align:right;
    }
    input[type="submit"]:before,button:after{
      content:'';
      position:absolute;
      top:0;
      right:0;
      height:2px;
      width:50%;
      background:#f8f8ff;
      transition:400ms ease all;
    }
    input[type="submit"]:after{
      right:inherit;
      top:inherit;
      left:0;
      bottom:0;
    }
    input[type="submit"]:hover:before,button:hover:after{
      width:50%;
      transition:800ms ease all;
    }
    #div1{
      padding-bottom: 80px;
      width: 100%;
      height: 140px;
      background-color: #a39ffa;
    }
    #div2{
      position: absolute;
      left: 50%;
      top:50%;
      transform: translate(-50%, -50%);
    }
    #div3 input{
        width:320px;
        height:30px;
    }
    #div3 {
        margin-bottom:20px;
    }
    </style>
</head>
<body>
 <header class="header_area">
     <div class="main_menu">
         <nav class="navbar navbar-expand-lg navbar-light">
             <div class="container box_1620">
                 <a class="navbar-brand logo_h" href="/"></a>
                 <a class="button" href="/">또바기</a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse"
                         data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                         aria-expanded="false" aria-label="Toggle navigation">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                 </button>

                 <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                     <ul class="nav navbar-nav menu_nav justify-content-end">
                         <li class="nav-item active"><a class="nav-link" href="/">HOME</a></li>
                         {% if user.is_authenticated %}
                         <li class="nav-item"><a class="nav-link" href="#" class="nav-link">반갑습니다, {{user.get_username}}님!</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" class="nav-link">로그아웃</a></li>
                         {% else %}
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" class="nav-link">로그인</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}" class="nav-link">회원가입</a></li>
                         {% endif %}
                         <li class="nav-item submenu dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">추천 테스트</a>
                         <ul class="dropdown-menu">
                             <li class="nav-item"><a class="nav-link" href="{%url 'recommendApp:recommend_index' %}">여행지 추천</a>
                             <li class="nav-item"><a class="nav-link" href="{%url 'c_type:index' %}">성격유형</a>
                         </ul></li>
<!--                         <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}" class="nav-link">커뮤니티</a></li>-->
                         <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                              aria-expanded="false">커뮤니티</a>
                            <ul class="dropdown-menu">
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}">글 목록</a></li>
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_upload' %}">글 작성</a></li>
                            </ul>
                         </li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'notice:notice' %}">공지사항</a></li>
                     </ul>
                 </div>
             </div>
         </nav>
     </div>
 </header>
<div class="container" style="position:relative; top:100px;">
  <div class="row" id ="div1">
  <h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 나에게 맞는 추천 여행지는? </h2>
    <p><b>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    간단한 테스트를 통해 나와 알맞는 여행지를 추천받을 수 있어요!
  </b></p>
  </div>
   <div class="row" id="div2">
   <form action="{% url 'recommendApp:recommend_result' %}" method="post">{% csrf_token %}
       <div class="rdo-grp">
           <h4> Q1. 여행할 때 교통수단은?</h4>
           <input type="radio" name="q1" value="1" id="c1"/>
           <label for="c1"><span></span><span>뚜벅이</span></label>
           <input type="radio" name="q1" value="2" id="c2"/>
           <label for="c2"><span></span><span>자차(혹은 렌트카)</span></label>
           <br><br>
           <h4>Q2. 동행자는 몇 명? </h4>
           <input type="radio" name="q2" value="1" id="c3"/>
           <label for="c3"><span></span><span>혼자</span></label>
           <input type="radio" name="q2" value="2" id="c4"/>
           <label for="c4"><span></span><span>2인</span></label>
           <input type="radio" name="q2" value="3" id="c5"/>
           <label for="c5"><span></span><span>3인 이상</span></label>
           <br><br>
           <h4>Q3. 내가 선호하는 여행 테마는?</h4>
           <input type="radio" name="q3" value="1" id="c6"/>
           <label for="c6"><span></span><span>관광</span></label>
           <input type="radio" name="q3" value="2" id="c7"/>
           <label for="c7"><span></span><span>휴양</span></label>
           <br><br>
       </div>
       <div id="div3">
           <h4>이름</h4>
           <input type="text" name="name">
           <p></p>
           <h4>만족했던 여행지</h4>
           <input type="text" name="local"><p></p>
           <h4>그 여행지의 평점(5점만점)</h4>
           <input type="text" name="rating">
       </div>

    <div style="margin-left: 30%;">
        <input type="submit" class="button" value="결과 보러가기">
    </div>
    </form>
   </div>
</div>
</body>
</html>

recommendApp/templates/recommend_result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>맞춤형 추천 여행지 테스트</title>
    <link rel="icon" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/img/Fevicon.png" type="image/png">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/themify-icons/themify-icons.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/linericon/style.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/flat-icon/font/flaticon.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/vendors/nice-select/nice-select.css">
    <link rel="stylesheet" href="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/css/style.css">
    <script src="https://ddobagi.s3.ap-northeast-2.amazonaws.com/static/js/main.js"></script>

  <style>
        .container{
      width: 100%;
      height: 100%;
    }
    html{
      width: 100%;
     height: 100%;
    }
    body {
      font-family: sans-serif;
      display: flex;
     background-color: #f8f8ff;
     width: 100%;
     height: 100%;

    }
    h2{
    color: white;
    padding-top: 30px;
    font-size: 50px;
    }
    #div1{
      text-align: center;
      padding-bottom: 60px;
      width: 100%;
      height: 140px;
      background-color: #a39ffa;
    }
    #div1 p{
      font-size: 25px;
      color: white;
    }
    #div2{
      font-size: 23px;
      text-align: center;
      padding-top: 75px;
    }
    </style>
</head>

 <header class="header_area">
     <div class="main_menu">
         <nav class="navbar navbar-expand-lg navbar-light">
             <div class="container box_1620">
                 <a class="navbar-brand logo_h" href="/"></a>
                 <a class="button" href="/">또바기</a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse"
                         data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                         aria-expanded="false" aria-label="Toggle navigation">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                 </button>

                 <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                     <ul class="nav navbar-nav menu_nav justify-content-end">
                         <li class="nav-item active"><a class="nav-link" href="/">HOME</a></li>
                         {% if user.is_authenticated %}
                         <li class="nav-item"><a class="nav-link" href="#" class="nav-link">반갑습니다, {{user.get_username}}님!</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" class="nav-link">로그아웃</a></li>
                         {% else %}
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" class="nav-link">로그인</a></li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}" class="nav-link">회원가입</a></li>
                         {% endif %}
                         <li class="nav-item submenu dropdown">
                         <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">추천 테스트</a>
                         <ul class="dropdown-menu">
                             <li class="nav-item"><a class="nav-link" href="{%url 'recommendApp:recommend_index' %}">여행지 추천</a>
                             <li class="nav-item"><a class="nav-link" href="{%url 'c_type:index' %}">성격유형</a>
                         </ul></li>
<!--                         <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}" class="nav-link">커뮤니티</a></li>-->
                         <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                              aria-expanded="false">커뮤니티</a>
                            <ul class="dropdown-menu">
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_list' %}">글 목록</a></li>
                              <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_upload' %}">글 작성</a></li>
                            </ul>
                         </li>
                         <li class="nav-item"><a class="nav-link" href="{% url 'notice:notice' %}">공지사항</a></li>
                     </ul>
                 </div>
             </div>
         </nav>
     </div>
 </header>
<body>
  <div class="container" style="position:relative; top:100px;">
  <div class="row" id="div1">
    <h2>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        나의 맞춤형 추천 여행지는?</h2>
   <br><br> <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       &nbsp;&nbsp;&nbsp;&nbsp;{{user.get_username}}님의 맞춤형 추천 여행지 결과 입니다!</p>
  </div>
  <div class="row" id="div2">
    <strong>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            맞춤형 추천 여행지는 "{{localtest}}" 입니다!</p>
  </strong>
  </div>
  </div>
</body>
</html>